### ISSUE TITLE
feat-request: svelte-persisted-states

### ISSUE THREAD

**Issue by saturnonearth** [joshnuss/svelte-persisted-store#264] opened 2024-05-29 01:52 UTC
Would it be difficult to port this library to use Svelte 5 `state` runes instead of `stores`?

**Comment by joshnuss** [comment] 2024-05-31 15:28
Hi @saturnonearth!

This is a duplicate of #251

So I'll close, but please follow that discussion and feel free to chime in!

**Closed by joshnuss** 2024-05-31 15:28 UTC
Labels: duplicate
